// src/types/EventPayload.ts
//
// This interface mirrors the payload generated by the k6 simulator.
// Keep it aligned with the ingest event contract.

export interface EventPayload {
  tenant_key: string;
  event_id: string;
  sensor_code: string;
  metric: string;
  value: number;
  unit: string;
  observed_at: string;
  scenario: string;
  data_profile: string;
  correlation_id?: string;
  trace_id?: string;
  tags?: Record<string, unknown>;
  raw_payload?: Record<string, unknown>;
}
